services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    ports:
      - 9187:9187
    environment:                      # rdsendpoint #rdspassword #database
      DATA_SOURCE_NAME: "postgresql://cloudgeeks-postgres.ckmishuf8m2v.us-east-1.rds.amazonaws.com:12345678@postgres:5432/shop?sslmode=disable"
    links:
      - prometheus