services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    ports:
      - 9187:9187
    environment:                      # dbname #password #rds-endpoint
      DATA_SOURCE_NAME: "postgresql://postgres:12345678@cloudgeeks-postgres-rds.cqrjzf7kbek3.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=disable"
